// MAINCATEGORY
export const CREATE_MAINCATEGORY="CREATE_MAINCATEGORY"                  ///FOR SAGA
export const CREATE_MAINCATEGORY_RED="CREATE_MAINCATEGORY_RED"          //FOR REDUCER

export const GET_MAINCATEGORY="GET_MAINCATEGORY"
export const GET_MAINCATEGORY_RED="GET_MAINCATEGORY_RED"

export const UPDATE_MAINCATEGORY="UPDATE_MAINCATEGORY"
export const UPDATE_MAINCATEGORY_RED="UPDATE_MAINCATEGORY_RED"

export const DELETE_MAINCATEGORY="DELETE_MAINCATEGORY"
export const DELETE_MAINCATEGORY_RED="DELETE_MAINCATEGORY_RED"

// SUBCATEGORY
export const CREATE_SUBCATEGORY="CREATE_SUBCATEGORY"                  ///FOR SAGA
export const CREATE_SUBCATEGORY_RED="CREATE_SUBCATEGORY_RED"          //FOR REDUCER

export const GET_SUBCATEGORY="GET_SUBCATEGORY"
export const GET_SUBCATEGORY_RED="GET_SUBCATEGORY_RED"

export const UPDATE_SUBCATEGORY="UPDATE_SUBCATEGORY"
export const UPDATE_SUBCATEGORY_RED="UPDATE_SUBCATEGORY_RED"

export const DELETE_SUBCATEGORY="DELETE_SUBCATEGORY"
export const DELETE_SUBCATEGORY_RED="DELETE_SUBCATEGORY_RED"
    